### ISSUE TITLE
Completing and Submitting CfA's Brigade Status Declaration Form

### ISSUE THREAD

**Issue by kcoronel** [hackforla/brigade-offboarding-process#1]
### Overview
As part of [CfA's announcement to changes to the Network team](https://discourse.codeforamerica.org/t/2023-network-announcements-and-reflections/1640), all Brigades will have to transition to independent brigades in 2023. As part of this offboarding Hack for LA will have to complete and submit CfA's Brigade Status Declaration Form by May 1, 2023.

### Action Items
- [x] Make a copy of the Brigade Status Declaration Form Worksheet 
- [x] Answer questions in Brigade Status Declaration Form Worksheet 
- [x] Submit Brigade Status Declaration Form on behalf of Hack for LA 

### Resources/Instructions
[Hack for LA Brigade Status Declaration [Response Worksheet]](https://docs.google.com/document/d/1atxKtSqZafiZI9a_ZUzNDXkshO7uxjsPoPRpHDlunWo/edit#heading=h.9e4t8juio475)
[Brigade Status Declaration Link](https://airtable.com/shrWhzOUHMqrCMh71)

**Comment by ExperimentsInHonesty** [comment]
completed and submitted
