### ISSUE TITLE
Complete and Submit CfA Notice of Termination Letter 

### ISSUE THREAD

**Issue by kcoronel** [hackforla/brigade-offboarding-process#2]
### Overview
As part of [CfA's announcement to changes to the Network team](https://discourse.codeforamerica.org/t/2023-network-announcements-and-reflections/1640), all Brigades will have to transition to independent brigades in 2023. As part of this offboarding Hack for LA will have to complete and submit CfA's Notice of Termination Letter by May 1, 2023.

### Action Items
- [x] Confirm receipt of Notice letter from CfA after March 15, 2023 
- [x] If needed create a worksheet to draft responses for Notice Letter 
- [x] Submit Notice Letter

**Comment by ExperimentsInHonesty** [comment]
Has been submitted and accepted
